### ISSUE TITLE
Example Contract / web3 js code for minting & saving to Arweave + IPFS

### ISSUE THREAD

**Issue by ozyman42** [m4thfr34k/Generative-Art#1]
I know you've only finished part 1 of your guide so far. Was wondering if there's some example repo or documentation out there that you're using for part 2 of your guide.

I'd be willing to help write your part 2 if you can help me out in pointing me to some existing examples.

**Comment by m4thfr34k** [comment]
Part 2 was in-progress up until the Metaplex Candy Machine was released. Candy Machine is a game-changer and completely changes the process for step 2. So, step 2 of the guide is being rewritten from the perspective of using this new tool. A guide has already been written by someone else, [here](https://hackmd.io/@levicook/HJcDneEWF?s=03), so that might be of some use to you until I'm finished with mine.

**Comment by ozyman42** [comment]
Thanks so much!
